"""add admin flag to group members

Revision ID: 315741339a2c
Revises: 8a88d06453d2
Create Date: 2026-01-16 19:44:36.998340

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '315741339a2c'
down_revision = '8a88d06453d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('group_member', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('group_member', schema=None) as batch_op:
        batch_op.drop_column('is_admin')

    # ### end Alembic commands ###
