"""CVLanguage

Revision ID: 40f11fde1cd3
Revises: e4ca652924d0
Create Date: 2026-05-24 22:09:30.009059

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40f11fde1cd3'
down_revision = 'e4ca652924d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cv_languages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_cv_id', sa.Integer(), nullable=False),
    sa.Column('language_name', sa.String(length=100), nullable=False),
    sa.Column('level', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_cv_id'], ['user_cvs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cv_languages')
    # ### end Alembic commands ###
