"""add cv template

Revision ID: 4361c180cb3d
Revises: 97d1de192819
Create Date: 2026-05-25 19:51:53.238653

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4361c180cb3d'
down_revision = '97d1de192819'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_cvs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cv_template', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_cvs', schema=None) as batch_op:
        batch_op.drop_column('cv_template')

    # ### end Alembic commands ###
