"""Create table offer

Revision ID: 449f7c7bc9be
Revises: 00c18d1e20a4
Create Date: 2025-10-17 19:30:20.409839

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '449f7c7bc9be'
down_revision = '00c18d1e20a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('offer_usage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('offer_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['offer_id'], ['offer.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('offer_usage')
    # ### end Alembic commands ###
