"""CVexperiencies

Revision ID: 653ef38025bb
Revises: 78783aa09aeb
Create Date: 2026-05-24 01:16:16.976277

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '653ef38025bb'
down_revision = '78783aa09aeb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cv_experiences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_cv_id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(length=150), nullable=False),
    sa.Column('job_title', sa.String(length=150), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('current_job', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_cv_id'], ['user_cvs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cv_experiences')
    # ### end Alembic commands ###
