"""Add UserCV

Revision ID: 78783aa09aeb
Revises: 2e4c8bc100e2
Create Date: 2026-05-23 19:34:16.192854

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78783aa09aeb'
down_revision = '2e4c8bc100e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_cvs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('full_name', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('email', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('phone', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('location', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('birth_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('profile_picture', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_cvs', schema=None) as batch_op:
        batch_op.drop_column('profile_picture')
        batch_op.drop_column('birth_date')
        batch_op.drop_column('location')
        batch_op.drop_column('phone')
        batch_op.drop_column('email')
        batch_op.drop_column('full_name')

    # ### end Alembic commands ###
