"""Add cv_file tu User

Revision ID: 8c4e5aea5bc9
Revises: a9e47f4b5614
Create Date: 2025-10-16 19:56:47.681976

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c4e5aea5bc9'
down_revision = 'a9e47f4b5614'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cv_file', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('cv_file')

    # ### end Alembic commands ###
