"""Add is_intro to Video

Revision ID: 8db27cca4644
Revises: ca4eaf91949f
Create Date: 2025-05-23 14:59:17.684192

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8db27cca4644'
down_revision = 'ca4eaf91949f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_intro', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.drop_column('is_intro')

    # ### end Alembic commands ###
