"""Add additional information to UserCV

Revision ID: 97d1de192819
Revises: 40f11fde1cd3
Create Date: 2026-05-24 23:53:35.859385

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97d1de192819'
down_revision = '40f11fde1cd3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_cvs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('additional_information', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_cvs', schema=None) as batch_op:
        batch_op.drop_column('additional_information')

    # ### end Alembic commands ###
