"""Add apple_sub to User

Revision ID: be5518fd38b9
Revises: 449f7c7bc9be
Create Date: 2025-12-11 20:47:10.360910

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be5518fd38b9'
down_revision = '449f7c7bc9be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('apple_sub', sa.String(length=255), nullable=True))
        batch_op.create_index(batch_op.f('ix_users_apple_sub'), ['apple_sub'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_apple_sub'))
        batch_op.drop_column('apple_sub')

    # ### end Alembic commands ###
