"""CVSkills

Revision ID: e4ca652924d0
Revises: 9f1da9b04887
Create Date: 2026-05-24 19:46:53.421238

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4ca652924d0'
down_revision = '9f1da9b04887'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cv_skills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_cv_id', sa.Integer(), nullable=False),
    sa.Column('skill_name', sa.String(length=150), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_cv_id'], ['user_cvs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cv_skills')
    # ### end Alembic commands ###
