"""add cv pdf

Revision ID: f56d469e22dd
Revises: 4361c180cb3d
Create Date: 2026-05-27 21:46:19.843841

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f56d469e22dd'
down_revision = '4361c180cb3d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_cvs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cv_pdf', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_cvs', schema=None) as batch_op:
        batch_op.drop_column('cv_pdf')

    # ### end Alembic commands ###
